server:
  port: ${PORT:8765}

spring:
  application:
    name: api-gateway

zuul:
  ignoredServices: '*'
  routes:
    product-service:
      path: /api/customers/**
      serviceId: customer-service
      stripPrefix: false
    shopping-list-service:
      path: /api/profiles/**
      serviceId: customer-profile-service
      stripPrefix: false
    spring-security-oauth-resource:
      path: /api/oauth-resource/**
      url: http://localhost:8767/oauth-resource
    oauth:
      path: /api/oauth/**
      url: http://localhost:8768/oauth-server/oauth
  sensitive-headers: Cookie,Set-Cookie

eureka:
  client:
    registerWithEureka: false

# Useful for debugging purposes
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
  
  
