server:
  port: ${PORT:8001}

spring:
  application:
    name: customer-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
  cloud:
    stream:
      bindings:
        customerDeletedOutput:
          destination: customerDeletedInput
          contentType: application/json
        customerUpdatedOutput:
          destination: customerUpdatedInput
          contentType: application/json
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true